#!/usr/bin/env bash
#
# Set the release version everywhere it lives.
#
#   packaging/set-version.sh 0.2.0
#
# Then: cargo build && git commit -am "release: 0.2.0" && git tag v0.2.0
#       && git push && git push --tags
#
# Three places, plus the lockfile:
#   1. src-tauri/Cargo.toml   — the source of truth (see version.sh)
#   2. website/src/consts.ts  — shown as prose on the site
#   3. Cargo.lock             — regenerated by cargo, never edited by hand;
#                               a stale lock fails every --locked build in CI
# tauri.conf.json deliberately has no `version` key: Tauri falls back to the
# crate version, which is one fewer thing to keep in step.
set -euo pipefail

NEW="${1:?usage: set-version.sh <x.y.z>}"
[[ "$NEW" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.-]+)?$ ]] || {
  echo "set-version.sh: '$NEW' is not a semver version" >&2; exit 1; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OLD="$("$ROOT/packaging/version.sh")"
echo "==> $OLD -> $NEW"

# Anchored to the [package] block so a dependency's version is never touched.
perl -0pi -e "s/(\[package\](?:.*?\n)*?version = )\"[^\"]*\"/\${1}\"$NEW\"/" \
  "$ROOT/src-tauri/Cargo.toml"

perl -pi -e "s/^(export const VERSION = )\"[^\"]*\";/\${1}\"$NEW\";/" \
  "$ROOT/website/src/consts.ts"

( cd "$ROOT" && cargo update --workspace --offline >/dev/null )

GOT="$("$ROOT/packaging/version.sh")"
[[ "$GOT" == "$NEW" ]] || { echo "set-version.sh: Cargo.toml still reads $GOT" >&2; exit 1; }
grep -q "\"$NEW\"" "$ROOT/website/src/consts.ts" || {
  echo "set-version.sh: website/src/consts.ts was not updated" >&2; exit 1; }

echo "==> done. Now: cargo build && git commit -am \"release: $NEW\" && git tag v$NEW"
